### ISSUE TITLE
Error: Command failed: ./installPackages.sh

### ISSUE THREAD

**Issue by tanahy** [citizenos/etherpad-lite-heroku#15]
I have followed the instructions correctly as far as I'm concern but I can't correctly deploy on Heroku. This is the log I get from `heroku logs --tail` :

`2021-01-16T12:22:09.144250+00:00` app[web.1]: "userColor": false,
2021-01-16T12:22:09.144250+00:00 app[web.1]: "rtl": false,
2021-01-16T12:22:09.144251+00:00 app[web.1]: "alwaysShowChat": false,
2021-01-16T12:22:09.144251+00:00 app[web.1]: "chatAndUsers": false,
2021-01-16T12:22:09.144251+00:00 app[web.1]: "lang": "en-gb"
2021-01-16T12:22:09.144252+00:00 app[web.1]: },
2021-01-16T12:22:09.144252+00:00 app[web.1]: "padShortcutEnabled": {
2021-01-16T12:22:09.144252+00:00 app[web.1]: "delete": true,
2021-01-16T12:22:09.144253+00:00 app[web.1]: "return": true,
2021-01-16T12:22:09.144253+00:00 app[web.1]: "pageUp": true,
2021-01-16T12:22:09.144253+00:00 app[web.1]: "pageDown": true
2021-01-16T12:22:09.144254+00:00 app[web.1]: },
2021-01-16T12:22:09.144254+00:00 app[web.1]: "suppressErrorsInPadText": false,
2021-01-16T12:22:09.144256+00:00 app[web.1]: "requireSession": false,
2021-01-16T12:22:09.144256+00:00 app[web.1]: "editOnly": false,
2021-01-16T12:22:09.144257+00:00 app[web.1]: "minify": true,
2021-01-16T12:22:09.144257+00:00 app[web.1]: "maxAge": 21600,
2021-01-16T12:22:09.144258+00:00 app[web.1]: "abiword": null,
2021-01-16T12:22:09.144258+00:00 app[web.1]: "soffice": null,
2021-01-16T12:22:09.144258+00:00 app[web.1]: "tidyHtml": null,
2021-01-16T12:22:09.144258+00:00 app[web.1]: "allowUnknownFileEnds": true,
2021-01-16T12:22:09.144259+00:00 app[web.1]: "requireAuthentication": false,
2021-01-16T12:22:09.144259+00:00 app[web.1]: "requireAuthorization": false,
2021-01-16T12:22:09.144260+00:00 app[web.1]: "trustProxy": false,
2021-01-16T12:22:09.144260+00:00 app[web.1]: "cookie": {
2021-01-16T12:22:09.144260+00:00 app[web.1]: "sameSite": "Lax"
2021-01-16T12:22:09.144260+00:00 app[web.1]: },
2021-01-16T12:22:09.144261+00:00 app[web.1]: "disableIPlogging": false,
2021-01-16T12:22:09.144261+00:00 app[web.1]: "automaticReconnectionTimeout": 0,
2021-01-16T12:22:09.144262+00:00 app[web.1]: "scrollWhenFocusLineIsOutOfViewport": {
2021-01-16T12:22:09.144262+00:00 app[web.1]: "percentage": {
2021-01-16T12:22:09.144262+00:00 app[web.1]: "editionAboveViewport": 0,
2021-01-16T12:22:09.144263+00:00 app[web.1]: "editionBelowViewport": 0
2021-01-16T12:22:09.144263+00:00 app[web.1]: },
2021-01-16T12:22:09.144263+00:00 app[web.1]: "duration": 0,
2021-01-16T12:22:09.144263+00:00 app[web.1]: "scrollWhenCaretIsInTheLastLineOfViewport": false,
2021-01-16T12:22:09.144264+00:00 app[web.1]: "percentageToScrollWhenUserPressesArrowUp": 0
2021-01-16T12:22:09.144264+00:00 app[web.1]: },
2021-01-16T12:22:09.144265+00:00 app[web.1]: "socketTransportProtocols": [
2021-01-16T12:22:09.144265+00:00 app[web.1]: "xhr-polling",
2021-01-16T12:22:09.144265+00:00 app[web.1]: "jsonp-polling",
2021-01-16T12:22:09.144266+00:00 app[web.1]: "htmlfile"
2021-01-16T12:22:09.144266+00:00 app[web.1]: ],
2021-01-16T12:22:09.144266+00:00 app[web.1]: "loadTest": false,
2021-01-16T12:22:09.144267+00:00 app[web.1]: "importExportRateLimiting": {
2021-01-16T12:22:09.144267+00:00 app[web.1]: "windowMs": 90000,
2021-01-16T12:22:09.144267+00:00 app[web.1]: "max": 10
2021-01-16T12:22:09.144268+00:00 app[web.1]: },
2021-01-16T12:22:09.144268+00:00 app[web.1]: "importMaxFileSize": 52428800,
2021-01-16T12:22:09.144268+00:00 app[web.1]: "commitRateLimiting": {
2021-01-16T12:22:09.144269+00:00 app[web.1]: "duration": 1,
2021-01-16T12:22:09.144269+00:00 app[web.1]: "points": 10
2021-01-16T12:22:09.144269+00:00 app[web.1]: },
2021-01-16T12:22:09.144270+00:00 app[web.1]: "exposeVersion": false,
2021-01-16T12:22:09.144270+00:00 app[web.1]: "loglevel": "INFO",
2021-01-16T12:22:09.144270+00:00 app[web.1]: "logconfig": {
2021-01-16T12:22:09.144271+00:00 app[web.1]: "appenders": [
2021-01-16T12:22:09.144271+00:00 app[web.1]: {
2021-01-16T12:22:09.144272+00:00 app[web.1]: "type": "console"
2021-01-16T12:22:09.144272+00:00 app[web.1]: }
2021-01-16T12:22:09.144272+00:00 app[web.1]: ]
2021-01-16T12:22:09.144273+00:00 app[web.1]: },
2021-01-16T12:22:09.144273+00:00 app[web.1]: "customLocaleStrings": {}
2021-01-16T12:22:09.144273+00:00 app[web.1]: }
2021-01-16T12:22:09.144339+00:00 app[web.1]: [2021-01-16T12:22:09.144] [INFO] start.js - 
2021-01-16T12:22:09.144340+00:00 app[web.1]: Write the Etherpad API key to the disk from the ENV "ETHERPAD_API_KEY" or local.json "___apiKey"...
2021-01-16T12:22:09.144400+00:00 app[web.1]: [2021-01-16T12:22:09.144] [INFO] start.js - ETHERPAD_API_KEY found!
2021-01-16T12:22:09.145572+00:00 app[web.1]: [2021-01-16T12:22:09.145] [INFO] start.js - 
2021-01-16T12:22:09.145573+00:00 app[web.1]: Write the Etherpad session key to the disk from the ENV "ETHERPAD_SESSION_KEY" or local.json "___sessionKey"...
2021-01-16T12:22:09.145666+00:00 app[web.1]: [2021-01-16T12:22:09.145] [INFO] start.js - ETHERPAD_SESSION_KEY found!
2021-01-16T12:22:09.145896+00:00 app[web.1]: [2021-01-16T12:22:09.145] [INFO] start.js - 
2021-01-16T12:22:09.145896+00:00 app[web.1]: Find plugin configuration from effective settings...
2021-01-16T12:22:09.146240+00:00 app[web.1]: [2021-01-16T12:22:09.146] [INFO] start.js - Installing plugins... npm install --no-save
2021-01-16T12:22:10.452880+00:00 app[web.1]: npm WARN etherpad-lite-heroku@1.0.3 No license field.
2021-01-16T12:22:10.453245+00:00 app[web.1]: 
2021-01-16T12:22:10.536795+00:00 app[web.1]: audited 15 packages in 0.68s
2021-01-16T12:22:10.537884+00:00 app[web.1]: found 0 vulnerabilities
2021-01-16T12:22:10.537885+00:00 app[web.1]: 
2021-01-16T12:22:10.553292+00:00 app[web.1]: Copy all ep_* packages from the /app/node_modules to etherpad_lite/node_modules
2021-01-16T12:22:10.553294+00:00 app[web.1]: To install ep-plugins, add them to package.json
2021-01-16T12:22:10.560321+00:00 app[web.1]: cp: cannot stat '../../node_modules/ep_*': No such file or directory
2021-01-16T12:22:10.561435+00:00 app[web.1]: child_process.js:651
2021-01-16T12:22:10.561436+00:00 app[web.1]: throw err;
2021-01-16T12:22:10.561437+00:00 app[web.1]: ^
2021-01-16T12:22:10.561437+00:00 app[web.1]: 
2021-01-16T12:22:10.561437+00:00 app[web.1]: Error: Command failed: ./installPackages.sh
2021-01-16T12:22:10.561439+00:00 app[web.1]: at checkExecSyncError (child_process.js:611:11)
2021-01-16T12:22:10.561439+00:00 app[web.1]: at Object.execSync (child_process.js:648:13)
2021-01-16T12:22:10.561440+00:00 app[web.1]: at Object.<anonymous> (/app/start.js:94:14)
2021-01-16T12:22:10.561440+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:688:30)
2021-01-16T12:22:10.561440+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
2021-01-16T12:22:10.561440+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:598:32)
2021-01-16T12:22:10.561441+00:00 app[web.1]: at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
2021-01-16T12:22:10.561441+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:529:3)
2021-01-16T12:22:10.561441+00:00 app[web.1]: at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
2021-01-16T12:22:10.561442+00:00 app[web.1]: at startup (internal/bootstrap/node.js:285:19)
2021-01-16T12:22:10.621254+00:00 heroku[web.1]: Process exited with status 1
2021-01-16T12:22:10.671629+00:00 heroku[web.1]: State changed from starting to crashed
2021-01-16T12:22:48.817707+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=boiling-cove-66332.herokuapp.com request_id=8620ef5e-86c9-4d8a-97d4-5221f8d81c11 fwd="148.81.47.202" dyno= connect= service= status=503 bytes= protocol=https
2021-01-16T12:28:21.196111+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=boiling-cove-66332.herokuapp.com request_id=95a4f31a-6b06-485e-a878-3af9e8baff1f fwd="148.81.47.202" dyno= connect= service= status=503 bytes= protocol=https
`

And this is my ETHERPAD_SETTINGS config variable in case I did something wrong here, which is highly possible as I cleaned the comments from the settings.json file with a script I quickly made and might have deleted something relevant.

`{"___apiKey":"${ETHERPAD_API_KEY}", "___sessionKey":"${ETHERPAD_SESSION_KEY}", "title": "Etherpad", "favicon": "favicon.ico", "skinName": "colibris", "skinVariants": "super-light-toolbar super-light-editor light-background", "ip": "0.0.0.0", "port": 9001, "showSettingsInAdminPage": true, "dbType": "dirty", "dbSettings": {"filename": "var/dirty.db"}, "defaultPadText": "Welcome to Etherpad!\n\nThis pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents!\n\nGet involved with Etherpad at https://etherpad.org\n", "padOptions": {"noColors": false, "showControls": true, "showChat": true, "showLineNumbers": true, "useMonospaceFont": false, "userName": false, "userColor": false, "rtl": false, "alwaysShowChat": false, "chatAndUsers": false, "lang": "en-gb"}, "padShortcutEnabled": {"delete": true, "return": true, "pageUp": true, "pageDown": true}, "suppressErrorsInPadText": false, "requireSession": false, "editOnly": false, "minify": true, "maxAge": 21600, "abiword": null, "soffice": null, "tidyHtml": null, "allowUnknownFileEnds": true, "requireAuthentication": false, "requireAuthorization": false, "trustProxy": false, "cookie": {"sameSite": "Lax"}, "disableIPlogging": false, "automaticReconnectionTimeout": 0, "scrollWhenFocusLineIsOutOfViewport": {"percentage": {"editionAboveViewport": 0, "editionBelowViewport": 0}, "duration": 0, "scrollWhenCaretIsInTheLastLineOfViewport": false, "percentageToScrollWhenUserPressesArrowUp": 0}, "socketTransportProtocols": ["xhr-polling", "jsonp-polling", "htmlfile"], "loadTest": false, "importExportRateLimiting": {"windowMs": 90000, "max": 10}, "importMaxFileSize": 52428800, "commitRateLimiting": {"duration": 1, "points": 10}, "exposeVersion": false, "loglevel": "INFO", "logconfig": {"appenders": [{"type": "console"}]}, "customLocaleStrings": {}}`

**Comment by tiblu** [comment]
@tanahy Sorry, for long delay. 
Did you manage to get it running?

**Comment by tanahy** [comment]
No problem. I didn't, sadly. Any suggestions?

**Comment by tiblu** [comment]
OK, please try again and provide recent data .

Take latest from GIT - https://github.com/citizenos/etherpad-lite-heroku.

Notes on (your) configuration:

* Use the example from the repo as the basis - https://github.com/citizenos/etherpad-lite-heroku/blob/master/config/local.json.example
     * **NOTE** Be aware that example contains plugins that you do not probably need. Basically it is OK to delete every property with `ep_` prefix.
* `__apiKey ` should be a valid string OR defined in Heroku environment variables 'ETHERPAD_API_KEY'. Do NOT use placeholders, they will not work.
* `___sessionKey` should be a valid string OR defined in Heroku environment variables 'ETHERPAD_SESSION_KEY'. Do NOT use placeholders, they will not work.
* NOTE: Autodeploys and deploys from Heroku UI WILL NOT work as the project uses submodules. You MUST use remotes and push to Heroku application GIT repository. (https://github.com/citizenos/etherpad-lite-heroku#heroku)

**Comment by tanahy** [comment]
Understood, it was quite a while ago but I think I took care of all 
those points but I will try again on the weekend with the latest 
version. Thanks and I will come back to you soon!

**Comment by tiblu** [comment]
@tanahy Any update on this?
