### ISSUE TITLE
Etherpad plugins disappearing when deploying to Heroku

### ISSUE THREAD

**Issue by valerioscisci** [citizenos/etherpad-lite-heroku#17]
Hello, I am running in an issue that I've ben trying to solve for a bit of time without success. Basically, I did set using the variable _ETHERPAD_SETTINGS_ the Etherpad configuration. When I deploy to Heroku I can see that along the process the plugins I want to install automatically on Etherpad get actually downloaded but then, they disappear. I attach the Heroku log and I have to say that locally I have no problem whatsoever!

Thanks to anyone answering me!

2021-11-10T11:54:36.573059+00:00 heroku[web.1]: Starting process with command `./start.js`
2021-11-10T11:54:37.438047+00:00 app[web.1]: [32m[2021-11-10T11:54:37.436] [INFO] start.js - [39mChecking for config/local.json...
2021-11-10T11:54:37.439363+00:00 app[web.1]: [32m[2021-11-10T11:54:37.438] [INFO] start.js - [39mlocal.json NOT found! Error: Cannot find module './config/local.json'
2021-11-10T11:54:37.439363+00:00 app[web.1]: Require stack:
2021-11-10T11:54:37.439363+00:00 app[web.1]: - /app/start.js
2021-11-10T11:54:37.439364+00:00 app[web.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-11-10T11:54:37.439364+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
2021-11-10T11:54:37.439364+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-11-10T11:54:37.439364+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:92:18)
2021-11-10T11:54:37.439365+00:00 app[web.1]:     at Object.<anonymous> (/app/start.js:19:21)
2021-11-10T11:54:37.439365+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-11-10T11:54:37.439365+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-11-10T11:54:37.439365+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-11-10T11:54:37.439366+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-11-10T11:54:37.439366+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
2021-11-10T11:54:37.439366+00:00 app[web.1]:   code: 'MODULE_NOT_FOUND',
2021-11-10T11:54:37.439366+00:00 app[web.1]:   requireStack: [ '/app/start.js' ]
2021-11-10T11:54:37.439367+00:00 app[web.1]: }
2021-11-10T11:54:37.439436+00:00 app[web.1]: [32m[2021-11-10T11:54:37.439] [INFO] start.js - [39mChecking for environment variable "ETHERPAD_SETTINGS"...
2021-11-10T11:54:37.439566+00:00 app[web.1]: [32m[2021-11-10T11:54:37.439] [INFO] start.js - [39mETHERPAD_SETTINGS found!
2021-11-10T11:54:37.439605+00:00 app[web.1]: [32m[2021-11-10T11:54:37.439] [INFO] start.js - [39mOverriding database configuration from DATABASE_URL!
2021-11-10T11:54:37.439648+00:00 app[web.1]: [32m[2021-11-10T11:54:37.439] [INFO] start.js - [39mMergeing config/local.json and "ETHERPAD_SETTINGS" configuration...
2021-11-10T11:54:37.440752+00:00 app[web.1]: [32m[2021-11-10T11:54:37.440] [INFO] start.js - [39mDB configuration seems to be a string, parsing it into object. See  https://github.com/ether/etherpad-lite/issues/4985
2021-11-10T11:54:37.441146+00:00 app[web.1]: [32m[2021-11-10T11:54:37.441] [INFO] start.js - [39mEffective configuration is:
2021-11-10T11:54:37.441147+00:00 app[web.1]:  {
2021-11-10T11:54:37.441147+00:00 app[web.1]:   "___apiKey": "XXXX",
2021-11-10T11:54:37.441147+00:00 app[web.1]:   "___sessionKey": "XXX",
2021-11-10T11:54:37.441148+00:00 app[web.1]:   "title": "Etherpad-Lite Heroku",
2021-11-10T11:54:37.441148+00:00 app[web.1]:   "favicon": "favicon.ico",
2021-11-10T11:54:37.441148+00:00 app[web.1]:   "ssl": false,
2021-11-10T11:54:37.441149+00:00 app[web.1]:   "dbType": "postgres",
2021-11-10T11:54:37.441149+00:00 app[web.1]:   "dbSettings": {
2021-11-10T11:54:37.441149+00:00 app[web.1]:     "type": "XXX",
2021-11-10T11:54:37.441149+00:00 app[web.1]:     "user": "XXX",
2021-11-10T11:54:37.441149+00:00 app[web.1]:     "password": "XXX",
2021-11-10T11:54:37.441149+00:00 app[web.1]:     "host": "XXX",
2021-11-10T11:54:37.441150+00:00 app[web.1]:     "port": "XXX",
2021-11-10T11:54:37.441150+00:00 app[web.1]:     "database": "XXX",
2021-11-10T11:54:37.441150+00:00 app[web.1]:     "ssl": "true"
2021-11-10T11:54:37.441150+00:00 app[web.1]:   },
2021-11-10T11:54:37.441150+00:00 app[web.1]:   "defaultPadText": "Topic content here..",
2021-11-10T11:54:37.441150+00:00 app[web.1]:   "requireSession": false,
2021-11-10T11:54:37.441151+00:00 app[web.1]:   "editOnly": false,
2021-11-10T11:54:37.441151+00:00 app[web.1]:   "sessionNoPassword": false,
2021-11-10T11:54:37.441151+00:00 app[web.1]:   "minify": false,
2021-11-10T11:54:37.441151+00:00 app[web.1]:   "maxAge": 21600,
2021-11-10T11:54:37.441151+00:00 app[web.1]:   "abiword": null,
2021-11-10T11:54:37.441152+00:00 app[web.1]:   "requireAuthentication": false,
2021-11-10T11:54:37.441152+00:00 app[web.1]:   "requireAuthorization": false,
2021-11-10T11:54:37.441152+00:00 app[web.1]:   "trustProxy": true,
2021-11-10T11:54:37.441152+00:00 app[web.1]:   "disableIPlogging": false,
2021-11-10T11:54:37.441152+00:00 app[web.1]:   "users": {
2021-11-10T11:54:37.441152+00:00 app[web.1]:     "admin": {
2021-11-10T11:54:37.441153+00:00 app[web.1]:       "password": "xxx",
2021-11-10T11:54:37.441153+00:00 app[web.1]:       "is_admin": true
2021-11-10T11:54:37.441153+00:00 app[web.1]:     }
2021-11-10T11:54:37.441153+00:00 app[web.1]:   },
2021-11-10T11:54:37.441153+00:00 app[web.1]:   "socketTransportProtocols": [
2021-11-10T11:54:37.441153+00:00 app[web.1]:     "xhr-polling",
2021-11-10T11:54:37.441154+00:00 app[web.1]:     "jsonp-polling",
2021-11-10T11:54:37.441154+00:00 app[web.1]:     "htmlfile"
2021-11-10T11:54:37.441154+00:00 app[web.1]:   ],
2021-11-10T11:54:37.441154+00:00 app[web.1]:   "loglevel": "DEBUG",
2021-11-10T11:54:37.441154+00:00 app[web.1]:   "logconfig": {
2021-11-10T11:54:37.441154+00:00 app[web.1]:     "appenders": [
2021-11-10T11:54:37.441154+00:00 app[web.1]:       {
2021-11-10T11:54:37.441155+00:00 app[web.1]:         "type": "console"
2021-11-10T11:54:37.441155+00:00 app[web.1]:       }
2021-11-10T11:54:37.441155+00:00 app[web.1]:     ]
2021-11-10T11:54:37.441155+00:00 app[web.1]:   },
2021-11-10T11:54:37.441155+00:00 app[web.1]:   "padOptions": {
2021-11-10T11:54:37.441155+00:00 app[web.1]:     "noColors": false,
2021-11-10T11:54:37.441155+00:00 app[web.1]:     "showControls": true,
2021-11-10T11:54:37.441155+00:00 app[web.1]:     "showChat": true,
2021-11-10T11:54:37.441156+00:00 app[web.1]:     "showLineNumbers": true,
2021-11-10T11:54:37.441156+00:00 app[web.1]:     "useMonospaceFont": false,
2021-11-10T11:54:37.441156+00:00 app[web.1]:     "userName": false,
2021-11-10T11:54:37.441156+00:00 app[web.1]:     "userColor": false,
2021-11-10T11:54:37.441156+00:00 app[web.1]:     "rtl": false,
2021-11-10T11:54:37.441156+00:00 app[web.1]:     "alwaysShowChat": false,
2021-11-10T11:54:37.441156+00:00 app[web.1]:     "chatAndUsers": false,
2021-11-10T11:54:37.441156+00:00 app[web.1]:     "lang": "en-gb"
2021-11-10T11:54:37.441157+00:00 app[web.1]:   },
2021-11-10T11:54:37.441157+00:00 app[web.1]:   "ep_auth_session": {
2021-11-10T11:54:37.441157+00:00 app[web.1]:     "___version": "1.1.1"
2021-11-10T11:54:37.441157+00:00 app[web.1]:   },
2021-11-10T11:54:37.441157+00:00 app[web.1]:   "ep_comments_page": {
2021-11-10T11:54:37.441160+00:00 app[web.1]:     "___version": "0.1.79"
2021-11-10T11:54:37.441160+00:00 app[web.1]:   }
2021-11-10T11:54:37.441160+00:00 app[web.1]: }
2021-11-10T11:54:37.441209+00:00 app[web.1]: [32m[2021-11-10T11:54:37.441] [INFO] start.js - [39m
2021-11-10T11:54:37.441210+00:00 app[web.1]: Write the Etherpad API key to the disk from the ENV "ETHERPAD_API_KEY" or local.json "___apiKey"...
2021-11-10T11:54:37.441257+00:00 app[web.1]: [32m[2021-11-10T11:54:37.441] [INFO] start.js - [39mETHERPAD_API_KEY found!
2021-11-10T11:54:37.441581+00:00 app[web.1]: [32m[2021-11-10T11:54:37.441] [INFO] start.js - [39m
2021-11-10T11:54:37.441582+00:00 app[web.1]: Write the Etherpad session key to the disk from the ENV "ETHERPAD_SESSION_KEY" or local.json "___sessionKey"...
2021-11-10T11:54:37.441632+00:00 app[web.1]: [32m[2021-11-10T11:54:37.441] [INFO] start.js - [39mETHERPAD_SESSION_KEY found!
2021-11-10T11:54:37.441733+00:00 app[web.1]: [32m[2021-11-10T11:54:37.441] [INFO] start.js - [39m
2021-11-10T11:54:37.441733+00:00 app[web.1]: Find plugin configuration from effective settings...
2021-11-10T11:54:37.441839+00:00 app[web.1]: [32m[2021-11-10T11:54:37.441] [INFO] start.js - [39mInstalling plugins... npm install --no-save ep_auth_session@1.1.1 ep_comments_page@0.1.79
2021-11-10T11:54:37.963979+00:00 app[web.1]: (node:18) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
2021-11-10T11:54:37.964001+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-11-10T11:54:38.179827+00:00 app[web.1]: npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
2021-11-10T11:54:38.345317+00:00 app[web.1]: npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
2021-11-10T11:54:39.592747+00:00 app[web.1]: npm WARN ep_comments_page@0.1.79 requires a peer of ep_etherpad-lite@>=1.8.6 but none is installed. You must install peer dependencies yourself.
2021-11-10T11:54:39.598731+00:00 app[web.1]: npm WARN etherpad-lite-heroku@1.0.4 No license field.
2021-11-10T11:54:39.598769+00:00 app[web.1]: 
2021-11-10T11:54:39.600101+00:00 app[web.1]: + ep_comments_page@0.1.79
2021-11-10T11:54:39.600102+00:00 app[web.1]: + ep_auth_session@1.1.1
2021-11-10T11:54:39.600103+00:00 app[web.1]: added 32 packages from 15 contributors and audited 17 packages in 1.75s
2021-11-10T11:54:39.617945+00:00 app[web.1]: 
2021-11-10T11:54:39.617948+00:00 app[web.1]: 3 packages are looking for funding
2021-11-10T11:54:39.617948+00:00 app[web.1]:   run `npm fund` for details
2021-11-10T11:54:39.617948+00:00 app[web.1]: 
2021-11-10T11:54:39.618372+00:00 app[web.1]: found 0 vulnerabilities
2021-11-10T11:54:39.618372+00:00 app[web.1]: 
2021-11-10T11:54:39.632100+00:00 app[web.1]: [32m[2021-11-10T11:54:39.631] [INFO] start.js - [39m
2021-11-10T11:54:39.632102+00:00 app[web.1]: Write settings.json file which is read by EP to /app/etherpad-lite/settings.json
2021-11-10T11:54:39.632575+00:00 app[web.1]: [32m[2021-11-10T11:54:39.632] [INFO] start.js - [39mSettings.json written to /app/etherpad-lite/settings.json
2021-11-10T11:54:39.632618+00:00 app[web.1]: [32m[2021-11-10T11:54:39.632] [INFO] start.js - [39mConfiguration done! 
2021-11-10T11:54:39.632619+00:00 app[web.1]: 
2021-11-10T11:54:39.820783+00:00 app[web.1]: Installing dependencies...
2021-11-10T11:54:40.250431+00:00 app[web.1]: npm WARN prepare removing existing node_modules/ before installation
2021-11-10T11:54:41.425655+00:00 app[web.1]: (node:70) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
2021-11-10T11:54:41.425666+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-11-10T11:54:51.265592+00:00 app[web.1]: added 503 packages in 11.024s
2021-11-10T11:54:51.274726+00:00 app[web.1]: Clearing minified cache...
2021-11-10T11:54:51.275921+00:00 app[web.1]: Starting Etherpad...
2021-11-10T11:54:51.340592+00:00 app[web.1]: [32m[2021-11-10 11:54:51.337] [INFO] settings - [39mAll relative paths will be interpreted relative to the identified Etherpad base dir: /app/etherpad-lite
2021-11-10T11:54:51.342469+00:00 app[web.1]: [32m[2021-11-10 11:54:51.342] [INFO] settings - [39msettings loaded from: /app/etherpad-lite/settings.json
2021-11-10T11:54:51.343832+00:00 app[web.1]: [32m[2021-11-10 11:54:51.343] [INFO] settings - [39mNo credentials file found in /app/etherpad-lite/credentials.json. Ignoring.
2021-11-10T11:54:51.344194+00:00 app[web.1]: [33m[2021-11-10 11:54:51.344] [WARN] settings - [39mUnknown Setting: 'sessionNoPassword'. This setting doesn't exist or it was removed
2021-11-10T11:54:51.344399+00:00 app[web.1]: [33m[2021-11-10 11:54:51.344] [WARN] settings - [39mNo "skinName" parameter found. Please check out settings.json.template and update your settings.json. Falling back to the default "colibris".
2021-11-10T11:54:51.344645+00:00 app[web.1]: [32m[2021-11-10 11:54:51.344] [INFO] settings - [39mUsing skin "colibris" in dir: /app/etherpad-lite/src/static/skins/colibris
2021-11-10T11:54:51.344718+00:00 app[web.1]: [36m[2021-11-10 11:54:51.344] [DEBUG] AbsolutePaths - [39mRelative path "./SESSIONKEY.txt" can be rewritten to "/app/etherpad-lite/SESSIONKEY.txt"
2021-11-10T11:54:51.344844+00:00 app[web.1]: [32m[2021-11-10 11:54:51.344] [INFO] settings - [39mSession key loaded from: /app/etherpad-lite/SESSIONKEY.txt
2021-11-10T11:54:51.345135+00:00 app[web.1]: [32m[2021-11-10 11:54:51.345] [INFO] settings - [39mRandom string used for versioning assets: c5cec09e
2021-11-10T11:54:51.360241+00:00 app[web.1]: [36m[2021-11-10 11:54:51.360] [DEBUG] console - [39mRunning on Node v14.17.6 (minimum required Node version: 12.13.0)
2021-11-10T11:54:51.571442+00:00 app[web.1]: [36m[2021-11-10 11:54:51.571] [DEBUG] runCmd - [39mExecuting command: npm --version
2021-11-10T11:54:51.571513+00:00 app[web.1]: [36m[2021-11-10 11:54:51.571] [DEBUG] runCmd - [39mcwd: /app/etherpad-lite
2021-11-10T11:54:51.571787+00:00 app[web.1]: [36m[2021-11-10 11:54:51.571] [DEBUG] runCmd - [39mPATH=/app/etherpad-lite/src/node_modules/.bin:/app/etherpad-lite/node_modules/.bin:/app/.heroku/node/bin:/app/.heroku/yarn/bin:/usr/local/bin:/usr/bin:/bin:/app/bin:/app/node_modules/.bin
2021-11-10T11:54:51.583223+00:00 app[web.1]: [32m[2021-11-10 11:54:51.583] [INFO] server - [39mStarting Etherpad...
2021-11-10T11:54:51.607950+00:00 app[web.1]: [31m[2021-11-10 11:54:51.607] [ERROR] console - [39m(node:31) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
2021-11-10T11:54:51.607951+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-11-10T11:54:51.632503+00:00 app[web.1]: [32m[2021-11-10 11:54:51.632] [INFO] plugins - [39mRunning npm to get a list of installed plugins...
2021-11-10T11:54:51.632576+00:00 app[web.1]: [36m[2021-11-10 11:54:51.632] [DEBUG] runCmd - [39mExecuting command: npm ls --long --json --depth=0 --no-production
2021-11-10T11:54:51.632674+00:00 app[web.1]: [36m[2021-11-10 11:54:51.632] [DEBUG] runCmd - [39mcwd: /app/etherpad-lite
2021-11-10T11:54:51.632860+00:00 app[web.1]: [36m[2021-11-10 11:54:51.632] [DEBUG] runCmd - [39mPATH=/app/etherpad-lite/src/node_modules/.bin:/app/etherpad-lite/node_modules/.bin:/app/.heroku/node/bin:/app/.heroku/yarn/bin:/usr/local/bin:/usr/bin:/bin:/app/bin:/app/node_modules/.bin
2021-11-10T11:54:51.772826+00:00 app[web.1]: [36m[2021-11-10 11:54:51.772] [DEBUG] runCmd - [39mCommand returned successfully: npm --version
2021-11-10T11:54:51.772908+00:00 app[web.1]: [32m[2021-11-10 11:54:51.772] [INFO] plugins - [39mnpm --version: 6.14.15
2021-11-10T11:54:54.287828+00:00 app[web.1]: [36m[2021-11-10 11:54:54.287] [DEBUG] runCmd - [39mCommand returned successfully: npm ls --long --json --depth=0 --no-production
2021-11-10T11:54:54.288511+00:00 app[web.1]: [32m[2021-11-10 11:54:54.288] [INFO] plugins - [39mLoading plugin ep_etherpad-lite...
2021-11-10T11:54:54.290133+00:00 app[web.1]: [32m[2021-11-10 11:54:54.290] [INFO] plugins - [39mLoaded 1 plugins
2021-11-10T11:54:54.856361+00:00 app[web.1]: [36m[2021-11-10 11:54:54.855] [DEBUG] AbsolutePaths - [39mRelative path "./APIKEY.txt" can be rewritten to "/app/etherpad-lite/APIKEY.txt"
2021-11-10T11:54:54.856500+00:00 app[web.1]: [32m[2021-11-10 11:54:54.856] [INFO] APIHandler - [39mApi key file read from: "/app/etherpad-lite/APIKEY.txt"
2021-11-10T11:54:54.907636+00:00 app[web.1]: [36m[2021-11-10 11:54:54.907] [DEBUG] server - [39mRemoving SIGINT listener because it might interfere with shutdown tasks. Function code:
2021-11-10T11:54:54.907638+00:00 app[web.1]: () => terminateWorkersAndMaster()
2021-11-10T11:54:54.907639+00:00 app[web.1]: Current stack:
2021-11-10T11:54:54.907640+00:00 app[web.1]:     at removeSignalListener (/app/etherpad-lite/src/node/server.js:81:36)
2021-11-10T11:54:54.907640+00:00 app[web.1]:     at process.<anonymous> (/app/etherpad-lite/src/node/server.js:138:9)
2021-11-10T11:54:54.907640+00:00 app[web.1]:     at process.emit (events.js:412:35)
2021-11-10T11:54:54.907641+00:00 app[web.1]:     at process.emit (domain.js:470:12)
2021-11-10T11:54:54.907641+00:00 app[web.1]:     at _addListener (events.js:443:14)
2021-11-10T11:54:54.907641+00:00 app[web.1]:     at process.addListener (events.js:497:10)
2021-11-10T11:54:54.907642+00:00 app[web.1]:     at initWorkerThreadsWorker (/app/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:134:13)
2021-11-10T11:54:54.907642+00:00 app[web.1]:     at selectWorkerImplementation (/app/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:219:16)
2021-11-10T11:54:54.907642+00:00 app[web.1]:     at Object.getWorkerImplementation (/app/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:230:26)
2021-11-10T11:54:54.907643+00:00 app[web.1]:     at Object.<anonymous> (/app/etherpad-lite/src/node_modules/threads/dist/master/index.js:13:39)
2021-11-10T11:54:54.907756+00:00 app[web.1]: [36m[2021-11-10 11:54:54.907] [DEBUG] server - [39mRemoving SIGTERM listener because it might interfere with shutdown tasks. Function code:
2021-11-10T11:54:54.907757+00:00 app[web.1]: () => terminateWorkersAndMaster()
2021-11-10T11:54:54.907757+00:00 app[web.1]: Current stack:
2021-11-10T11:54:54.907757+00:00 app[web.1]:     at removeSignalListener (/app/etherpad-lite/src/node/server.js:81:36)
2021-11-10T11:54:54.907757+00:00 app[web.1]:     at process.<anonymous> (/app/etherpad-lite/src/node/server.js:138:9)
2021-11-10T11:54:54.907757+00:00 app[web.1]:     at process.emit (events.js:412:35)
2021-11-10T11:54:54.907758+00:00 app[web.1]:     at process.emit (domain.js:470:12)
2021-11-10T11:54:54.907758+00:00 app[web.1]:     at _addListener (events.js:443:14)
2021-11-10T11:54:54.907758+00:00 app[web.1]:     at process.addListener (events.js:497:10)
2021-11-10T11:54:54.907758+00:00 app[web.1]:     at initWorkerThreadsWorker (/app/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:135:13)
2021-11-10T11:54:54.907759+00:00 app[web.1]:     at selectWorkerImplementation (/app/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:219:16)
2021-11-10T11:54:54.907759+00:00 app[web.1]:     at Object.getWorkerImplementation (/app/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:230:26)
2021-11-10T11:54:54.907760+00:00 app[web.1]:     at Object.<anonymous> (/app/etherpad-lite/src/node_modules/threads/dist/master/index.js:13:39)
2021-11-10T11:54:54.925966+00:00 app[web.1]: [32m[2021-11-10 11:54:54.925] [INFO] server - [39mInstalled plugins: 
2021-11-10T11:54:54.926130+00:00 app[web.1]: [36m[2021-11-10 11:54:54.926] [DEBUG] server - [39mInstalled parts:
2021-11-10T11:54:54.926131+00:00 app[web.1]: ep_etherpad-lite/openapi
2021-11-10T11:54:54.926131+00:00 app[web.1]: ep_etherpad-lite/adminsettings
2021-11-10T11:54:54.926131+00:00 app[web.1]: ep_etherpad-lite/adminplugins
2021-11-10T11:54:54.926132+00:00 app[web.1]: ep_etherpad-lite/admin
2021-11-10T11:54:54.926132+00:00 app[web.1]: ep_etherpad-lite/tests
2021-11-10T11:54:54.926132+00:00 app[web.1]: ep_etherpad-lite/socketio
2021-11-10T11:54:54.926132+00:00 app[web.1]: ep_etherpad-lite/errorhandling
2021-11-10T11:54:54.926133+00:00 app[web.1]: ep_etherpad-lite/importexport
2021-11-10T11:54:54.926133+00:00 app[web.1]: ep_etherpad-lite/apicalls
2021-11-10T11:54:54.926133+00:00 app[web.1]: ep_etherpad-lite/webaccess
2021-11-10T11:54:54.926133+00:00 app[web.1]: ep_etherpad-lite/padurlsanitize
2021-11-10T11:54:54.926134+00:00 app[web.1]: ep_etherpad-lite/specialpages
2021-11-10T11:54:54.926134+00:00 app[web.1]: ep_etherpad-lite/i18n
2021-11-10T11:54:54.926134+00:00 app[web.1]: ep_etherpad-lite/stats
2021-11-10T11:54:54.926134+00:00 app[web.1]: ep_etherpad-lite/static
2021-11-10T11:54:54.926134+00:00 app[web.1]: ep_etherpad-lite/express
2021-11-10T11:54:54.926135+00:00 app[web.1]: ep_etherpad-lite/Minify
2021-11-10T11:54:54.926135+00:00 app[web.1]: ep_etherpad-lite/DB
2021-11-10T11:54:54.943477+00:00 app[web.1]: [36m[2021-11-10 11:54:54.943] [DEBUG] server - [39mInstalled server-side hooks:
2021-11-10T11:54:54.943478+00:00 app[web.1]:   createServer:
2021-11-10T11:54:54.943479+00:00 app[web.1]:     ep_etherpad-lite:
2021-11-10T11:54:54.943480+00:00 app[web.1]:       express: ep_etherpad-lite/node/hooks/express
2021-11-10T11:54:54.943480+00:00 app[web.1]:   expressCloseServer:
2021-11-10T11:54:54.943481+00:00 app[web.1]:     ep_etherpad-lite:
2021-11-10T11:54:54.943481+00:00 app[web.1]:       socketio: ep_etherpad-lite/node/hooks/express/socketio
2021-11-10T11:54:54.943481+00:00 app[web.1]:   expressConfigure:
2021-11-10T11:54:54.943482+00:00 app[web.1]:     ep_etherpad-lite:
2021-11-10T11:54:54.943482+00:00 app[web.1]:       webaccess: ep_etherpad-lite/node/hooks/express/webaccess
2021-11-10T11:54:54.943484+00:00 app[web.1]:   expressCreateServer:
2021-11-10T11:54:54.943485+00:00 app[web.1]:     ep_etherpad-lite:
2021-11-10T11:54:54.943485+00:00 app[web.1]:       admin: ep_etherpad-lite/node/hooks/express/admin
2021-11-10T11:54:54.943486+00:00 app[web.1]:       adminplugins: ep_etherpad-lite/node/hooks/express/adminplugins
2021-11-10T11:54:54.943486+00:00 app[web.1]:       adminsettings: ep_etherpad-lite/node/hooks/express/adminsettings
2021-11-10T11:54:54.943487+00:00 app[web.1]:       apicalls: ep_etherpad-lite/node/hooks/express/apicalls
2021-11-10T11:54:54.943487+00:00 app[web.1]:       errorhandling: ep_etherpad-lite/node/hooks/express/errorhandling
2021-11-10T11:54:54.943488+00:00 app[web.1]:       i18n: ep_etherpad-lite/node/hooks/i18n
2021-11-10T11:54:54.943488+00:00 app[web.1]:       importexport: ep_etherpad-lite/node/hooks/express/importexport
2021-11-10T11:54:54.943488+00:00 app[web.1]:       openapi: ep_etherpad-lite/node/hooks/express/openapi
2021-11-10T11:54:54.943489+00:00 app[web.1]:       padurlsanitize: ep_etherpad-lite/node/hooks/express/padurlsanitize
2021-11-10T11:54:54.943489+00:00 app[web.1]:       socketio: ep_etherpad-lite/node/hooks/express/socketio
2021-11-10T11:54:54.943489+00:00 app[web.1]:       specialpages: ep_etherpad-lite/node/hooks/express/specialpages
2021-11-10T11:54:54.943490+00:00 app[web.1]:       static: ep_etherpad-lite/node/hooks/express/static
2021-11-10T11:54:54.943490+00:00 app[web.1]:       tests: ep_etherpad-lite/node/hooks/express/tests
2021-11-10T11:54:54.943491+00:00 app[web.1]:   restartServer:
2021-11-10T11:54:54.943491+00:00 app[web.1]:     ep_etherpad-lite:
2021-11-10T11:54:54.943492+00:00 app[web.1]:       express: ep_etherpad-lite/node/hooks/express
2021-11-10T11:54:54.943492+00:00 app[web.1]:   shutdown:
2021-11-10T11:54:54.943492+00:00 app[web.1]:     ep_etherpad-lite:
2021-11-10T11:54:54.943493+00:00 app[web.1]:       DB: ep_etherpad-lite/node/db/DB
2021-11-10T11:54:54.943493+00:00 app[web.1]:       express: ep_etherpad-lite/node/hooks/express
2021-11-10T11:54:54.943494+00:00 app[web.1]:       Minify: ep_etherpad-lite/node/utils/Minify
2021-11-10T11:54:54.943494+00:00 app[web.1]:       stats: ep_etherpad-lite/node/stats
2021-11-10T11:54:54.943494+00:00 app[web.1]:   socketio:
2021-11-10T11:54:54.943495+00:00 app[web.1]:     ep_etherpad-lite:
2021-11-10T11:54:54.943495+00:00 app[web.1]:       adminplugins: ep_etherpad-lite/node/hooks/express/adminplugins
2021-11-10T11:54:54.943495+00:00 app[web.1]:       adminsettings: ep_etherpad-lite/node/hooks/express/adminsettings
2021-11-10T11:54:54.943496+00:00 app[web.1]:       socketio: ep_etherpad-lite/node/handler/PadMessageHandler
2021-11-10T11:54:54.944253+00:00 app[web.1]: [32m[2021-11-10 11:54:54.944] [INFO] console - [39mReport bugs at https://github.com/ether/etherpad-lite/issues
2021-11-10T11:54:54.944703+00:00 app[web.1]: [33m[2021-11-10 11:54:54.944] [WARN] settings - [39mCan't get git version for server header
2021-11-10T11:54:54.944704+00:00 app[web.1]: ENOENT: no such file or directory, lstat '/app/etherpad-lite/.git'
2021-11-10T11:54:54.944866+00:00 app[web.1]: [33m[2021-11-10 11:54:54.944] [WARN] settings - [39mCan't get git version for server header
2021-11-10T11:54:54.944867+00:00 app[web.1]: ENOENT: no such file or directory, lstat '/app/etherpad-lite/.git'
2021-11-10T11:54:54.944928+00:00 app[web.1]: [32m[2021-11-10 11:54:54.944] [INFO] console - [39mYour Etherpad version is 1.8.14 ()
2021-11-10T11:54:56.125543+00:00 app[web.1]: [32m[2021-11-10 11:54:56.125] [INFO] http - [39mHTTP server listening for connections
2021-11-10T11:54:56.125617+00:00 app[web.1]: [32m[2021-11-10 11:54:56.125] [INFO] console - [39mYou can access your Etherpad instance at http://0.0.0.0:32801/
2021-11-10T11:54:56.125755+00:00 app[web.1]: [32m[2021-11-10 11:54:56.125] [INFO] console - [39mThe plugin admin page is at http://0.0.0.0:32801/admin/plugins
2021-11-10T11:54:56.125842+00:00 app[web.1]: [32m[2021-11-10 11:54:56.125] [INFO] server - [39mEtherpad is running

**Comment by valerioscisci** [comment]
Guys I finally managed to fix it. I really don't know how that is possible but, the script installPackages.sh was different that the version that is in this repo. Basically on line 11 I had 

 `cp -R ../../node_modules/ep_* .`
 instead of
` cp -R ../../node_modules/ep_* .`

Really no idea how that happend as I just downloaded the pushed to heroku...

Well the issue can be closed now!
